# This file contains the information needed for Shopify to authenticate
# requests and edit/update your remote theme files.
#
# 1. Set up a private app (https://help.shopify.com/api/guides/api-credentials#generate-private-app-credentials)
#    with "Read and write" permissions for "Theme templates and theme assets".
# 2. Replace the required variables for each environment below.
#
# password, theme_id, and store variables are required.
#
# For more information on this config file:
#   Configuration variables | http://shopify.github.io/themekit/configuration/
#   Ignore patterns | http://shopify.github.io/themekit/ignores/

---

development:
  password: 80571b7421438cfd1a91f2476185e6ba
  theme_id: 12237242404
  store: sarah-tempest.myshopify.com
  ignore_files:

production:
  password: 80571b7421438cfd1a91f2476185e6ba
  theme_id: 12237242404
  store: sarah-tempest.myshopify.com
  ignore_files: